SUPABASE_URL = "https://qeeajsquggrolobiqffa.supabase.co"
SUPABASE_KEY = "sb_publishable_d_cAUhTVwqmtJgwxNMt6hg_GwDUsrU4"
SUPABASE_EVALUATIONS_TABLE = "evaluations"
SUPABASE_DATASETS_TABLE = "dataset_rows"
